version: '3.9'
services:
  uvicorn:
    build: .
    command: uvicorn src.agents.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"

  streamlit:
    build: .
    command: streamlit run src/chatbot_interface.py --server.address=0.0.0.0 --server.port=8501
    ports:
      - "8501:8501"