version: '3.9'
services:
  uvicorn:
    build:
      context: .
    command: uvicorn src.agents.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
          - /Users/z3542407/Documents/GitHub/crypto-supporter-agent:/workspaces/ai-agent


  streamlit:
    build:
      context: .
    command: streamlit run src/chatbot_interface.py --server.address=0.0.0.0 --server.port=8501
    ports:
      - "8501:8501"
    networks:
      - app-network
    volumes:
          - /Users/z3542407/Documents/GitHub/crypto-supporter-agent:/workspaces/ai-agent


networks:
  app-network: