version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant:v1.0.0
    container_name: qdrant
    ports:
      - "4444:6333"   # Expose Qdrant internal port 6333 on port 4444
    volumes:
      - qdrant_storage:/qdrant/storage  # Store Qdrant data persistently

  ai-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-agent
    depends_on:
      - qdrant
    environment:
      QDRANT_HOST: "qdrant"
      QDRANT_PORT: 4444
    volumes:
      - .:/workspaces/ai-agent

volumes:
  qdrant_storage:
